from collections.abc import Mapping, Sequence, Set

__version__: str

class ExchangeError(ValueError): ...
class InvalidExchange(ExchangeError): ...
class DimensionError(ExchangeError): ...
class DomainError(ExchangeError): ...
class CapacityError(ExchangeError): ...
class ConstraintError(ExchangeError): ...
class ParticipationError(ExchangeError): ...
class DuplicateExchangeError(ExchangeError): ...
class StalePreparationError(ExchangeError): ...
class ForeignPreparationError(ExchangeError): ...
class SnapshotError(ExchangeError): ...

class Dimension:
    def __init__(self, name: str | None = None) -> None: ...
    def product(self, other: Dimension) -> Dimension: ...
    def quotient(self, other: Dimension) -> Dimension: ...
    @property
    def powers(self) -> dict[str, int]: ...
    def __eq__(self, other: object) -> bool: ...

class Quantity:
    def __init__(self, value: str, dimension: Dimension | None = None) -> None: ...
    @property
    def fraction(self) -> str: ...
    @property
    def dimension(self) -> Dimension: ...
    def __eq__(self, other: object) -> bool: ...

class Expr:
    @staticmethod
    def constant(value: Quantity) -> Expr: ...
    @staticmethod
    def before(slot: str) -> Expr: ...
    @staticmethod
    def after(slot: str) -> Expr: ...
    @staticmethod
    def delta(slot: str) -> Expr: ...
    @staticmethod
    def boundary(port: str) -> Expr: ...
    @staticmethod
    def fact(name: str) -> Expr: ...
    @staticmethod
    def sum(terms: Sequence[Expr]) -> Expr: ...
    def product(self, other: Expr) -> Expr: ...
    def quotient(self, other: Expr) -> Expr: ...

class Constraint:
    def __init__(self, id: str, left: Expr, right: Expr, *, less_or_equal: bool = False, absolute: str = "0", relative: str = "0") -> None: ...

class Fact:
    def __init__(self, owner: str, dimension: Dimension) -> None: ...

class Capacity:
    def __init__(self, maximum: Quantity) -> None: ...

class Stock:
    def __init__(self, id: str, owner: str, dimension: Dimension, *, signed: bool = False, capacities: Mapping[str, Quantity] | None = None) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def owner(self) -> str: ...
    @property
    def dimension(self) -> Dimension: ...
    @property
    def signed(self) -> bool: ...

class Placement:
    def __init__(self, owner: str, capacities: Mapping[str, Quantity] | None = None) -> None: ...

class Law:
    def __init__(self, id: str, slots: Mapping[str, Dimension], constraints: Sequence[Constraint], *, boundaries: Mapping[str, Dimension] | None = None, facts: Mapping[str, Fact] | None = None, participants: Set[str] | None = None) -> None: ...

class Model:
    def __init__(self, owners: Set[str], laws: Sequence[Law], capacities: Mapping[str, Capacity] | None = None) -> None: ...

class Exchange:
    def __init__(self, id: str, law: str, bindings: Mapping[str, str], *, deltas: Mapping[str, Quantity] | None = None, boundaries: Mapping[str, Quantity] | None = None, creates: Sequence[Stock] | None = None, removes: Set[str] | None = None, moves: Mapping[str, Placement] | None = None, declarations: Model | None = None) -> None: ...
    @property
    def id(self) -> str: ...

class RecordWrite:
    def __init__(self, key: str, value: bytes | None) -> None: ...

class Participation: ...
class Prepared: ...

class Receipt:
    @property
    def id(self) -> str: ...
    @property
    def revision(self) -> int: ...
    @property
    def law(self) -> str: ...
    @property
    def boundaries(self) -> dict[str, Quantity]: ...
    @property
    def changes(self) -> dict[str, tuple[Quantity, Quantity]]: ...
    def __eq__(self, other: object) -> bool: ...

class Engine:
    def __init__(self, owners: Set[str], laws: Sequence[Law], capacities: Mapping[str, Capacity] | None = None) -> None: ...
    @property
    def revision(self) -> int: ...
    def amount(self, stock: str) -> Quantity: ...
    def stock(self, stock: str) -> Stock: ...
    def record(self, owner: str, key: str) -> bytes | None: ...
    def receipt(self, id: str) -> Receipt | None: ...
    def participate(self, owner: str, exchange: Exchange, writes: Sequence[RecordWrite] | None = None, facts: Mapping[str, Quantity] | None = None) -> Participation: ...
    def prepare(self, exchange: Exchange, participants: Sequence[Participation] | None = None) -> Prepared: ...
    def publish(self, prepared: Prepared) -> Receipt: ...
    def snapshot(self) -> bytes: ...
    @staticmethod
    def restore(bytes: bytes) -> Engine: ...
